language: ruby
sudo: false
rvm:
  - 2.2.4
  - 2.3.0
env:
  - DB=postgresql
install: bundle install
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - psql -c 'create database demoapp_test' -U postgres
